/*
 * Contenido.java
 *
 * Created on 24 de diciembre de 2007, 02:03 PM
 */

package jpositionrating;

/**
 *
 * @author  Usuaio
 */
public class Contenido extends javax.swing.JFrame {
    
    /** Creates new form Contenido */
    public Contenido() {
        initComponents();
        Combo();
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jProgressBar2 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Contenido de ayuda");
        setResizable(false);
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Evaluación de puesto", "Regresión aritmética", "Regresión geométrica" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(10, 10, 160, 20);

        jProgressBar2.setIndeterminate(true);
        getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(0, 250, 460, 10);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 430, 180);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-459)/2, (screenSize.height-286)/2, 459, 286);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
// TODO: Agrege su codigo aqui:
        Combo();
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    
    public void Combo()
    {
        if(jComboBox1.getSelectedIndex() == 0)
            jTextArea1.setText("Es un sistema técnico para determinar la importancia \n" + "de cada puesto en relación con los demás de una \n" + "empresa logrando una correcta organización y \n" + "remuneración del personal, estableciendo un conjunto \n" + "ordenado de principios y reglas, fundamentado en \n" + "elementos objetivos y cientificos que son necesarios a \n" + "partir de la descripción de cada cargo, donde se \n" + "determinan las funciones básicas a analizar y luego \n" + "valorar");
        
        if(jComboBox1.getSelectedIndex() == 1)
            jTextArea1.setText("La regresión aritmética se utiliza solo para empresas manufactureras");
        
        if(jComboBox1.getSelectedIndex() == 2)
            jTextArea1.setText("La regresión geométrica se utiliza solo para puestos de oficina");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
